version: '3.1'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: moviesdb
    volumes:
      - moviedb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: postgres_movie_db

  spring-api:
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - db
    container_name: spring_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/moviesdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update


volumes:
  moviedb: