spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moviesdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  devtools:
    restart:
      log-condition-evaluation-delta: true
server:
  port: 8081
  error:
    include-message: always
