# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# Test application
# Deploy to Docker hub
# Deploy to Heroku

name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]
jobs:
  build_test_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: maven build, clean
        run: |
          mvn clean package
      - name: test
        run: mvn test
#      - name: Deploy to Heroku
#        if: ${{ github.ref_name == 'main' }}
#        uses: akhileshns/heroku-deploy@v3.12.12 # This is the actual action
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_app_name: "spring-movies-api" # should be unique
#          heroku_email: "youneslamkhanter02@gmail.com"
      - name: Push to Docker Hub
        if: ${{ github.ref_name == 'main' }}
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: peterevans/dockerhub-description
          short-description: ${{ github.event.repository.description }}


